### ISSUE TITLE
Error when executing the Android sample

### ISSUE THREAD

**Issue by daMatz** [sinch/rtc-reference-applications#1]
I get the following error when trying to run the android sample application:

```
\rtc-reference-applications\android\app\build\tmp\kapt3\stubs\debug\com\sinch\rtc\vvc\reference\app\storage\converters\VideoScalingTypeConverter.java:21: error: Invalid return type for a type converter.
    public final error.NonExistentClass fromCallType(@org.jetbrains.annotations.NotNull
```

**Comment by 0xROLANDIAN** [comment]
Sorry for lateness on this one.  If you open a ticket here:  https://tickets.sinch.com/plugins/servlet/desk/portal/31/ we can try and discern what the problem is.  Are you running the reference apps in an emulator for instance?

**Comment by roland-sinch** [comment]
Sorry for lateness on this one. If you open a ticket here: https://tickets.sinch.com/plugins/servlet/desk/portal/31/ we can try and discern what the problem is. Are you running the reference apps in an emulator for instance?
